### PR TITLE
IGVF-1776-rm-library-construction

### PR DESCRIPTION
**Pull request by meenakshikagda**

### CODE REVIEW

**Review by jenjou — APPROVED** [review]

**Review by ian-whaling — CHANGES_REQUESTED** [review]
Can you also remove it from facets?

**Review by ian-whaling — CHANGES_REQUESTED** [review]
Also remove from facet_groups and search columns below.

**Comment by jenjou** [comment]
Thanks @ian-whaling for catching that, I think there is one more line that needs to be removed from that file (it is in the "Facet groups" section lower in the file)

**Review by ian-whaling — DISMISSED** [review]

**Comment by meenakshikagda** [comment]
> Thanks @ian-whaling for catching that, I think there is one more line that needs to be removed from that file (it is in the "Facet groups" section lower in the file)

I think everything is addressed now. Am I still missing something @jenjou ?

**Comment by jenjou** [comment]
> > Thanks @ian-whaling for catching that, I think there is one more line that needs to be removed from that file (it is in the "Facet groups" section lower in the file)
> 
> I think everything is addressed now. Am I still missing something @jenjou ?

No, I think it is fine. I was looking at an old version of your PR and did not refresh it so I didn't see the new commit you made

**Pull request merged**
