### PR TITLE
IGVF-435-reconcile-human-donor

### PR DESCRIPTION
**Pull request by dougli1sqrd**
Fixing a typo in the description of references in mixins schema.

Previously it said `A reference that provide smore information about the object` and now it says `A reference that provides more information`.

### CODE REVIEW

**Review by forresttanaka — DISMISSED** [review]
OK, I got completely confused. I didn’t realize you had an igvfd ticket under the same ticket number as an igvf-ui ticket. I think this really needed a new ticket. I don’t think we use the `description` property yet, though we might in encoded.

**Comment by hitz** [comment]
Should this PR be closed @gabdank @forresttanaka

**Comment by hitz** [comment]
ticket is already merged?

**Comment by forresttanaka** [comment]
It’s not merged. The igvf-ui branch of IGVF-435 is merged, but the igvfd one isn’t. I told Eric in the future we need different tickets for the igvfd and igvf-ui portions of one fix, because this is really confusing.

**Pull request closed without merging**
