### PR TITLE
IGVF-55-linting

### PR DESCRIPTION
**Pull request by ottojolanki**
applied isort, autopep8, single-quote and end of line fixer

### CODE REVIEW

**Comment by keenangraham** [comment]
I think we want to drop isort and maybe try adding JSON and YML checkers and maybe flake8?

**Comment by cricketsloan** [comment]
I agree that a json formatter would be excellent.

**Comment by ottojolanki** [comment]
added pretty-format-json.

**Review by keenangraham — DISMISSED** [review]
Will need to rebase before merge.

**Comment by forresttanaka** [comment]
I don’t know if this branch fixes this, but one thing I noticed with insert data is that prettier fixes those JSON files too, and it changed arrays to always have line breaks in them:
```
"prop": [
    "item1"
]
```
and it also corrected some incorrect indentation that was in the file (e.g. 7 spaces of indent instead of 8). I ended up having to turn off prettier for JSON files, but that seemed like a shame that I had to let go of the legitimate fixes it put in.

**Comment by ottojolanki** [comment]
@forresttanaka  it should indent with 4 spaces and do "pretty formatting" so hopefully it is the same thing.

**Comment by ottojolanki** [comment]
Could someone double check that `src/igvfd/tests/data/inserts/lab.json` and `src/igvfd/schemas/lab.json` are the way they need to be just in case.

**Comment by cricketsloan** [comment]
Is there another competitor to prettier?  Or a version.  I see what Forrest is talking about, the breaking out of all of the all of the brackets is no "prettier"

        { "$ref": "mixins.json#/shared_status" }

is being changed to:

        {
            "$ref": "mixins.json#/schema_version"
        },

Possibly we live with this as it does find lots of other things

**Review by keenangraham — APPROVED** [review]
Think these are good changes, glad circle will run independent check.

I think the JSON multiline formatting is more consistent overall.

Sort of dragging Python back into repo dependency but seems disconnected enough from app (and only requires one time install?) that probably more useful than not.

Maybe should pin pip install: `pip install pre-commit==2.17.0`?

**Review by keenangraham — APPROVED** [review]

**Pull request merged**
